const $ = id => document.getElementById(id);
const STORAGE = { favorites:'dunya.course.favorites', recent:'dunya.course.recent', views:'dunya.course.views', theme:'dunya.theme' };
function readJSON(key, fallback){ try{return JSON.parse(localStorage.getItem(key))??fallback}catch(_){return fallback} }
function writeJSON(key,value){ try{localStorage.setItem(key,JSON.stringify(value))}catch(_){} }
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function showToast(message){const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast._t);showToast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem(STORAGE.theme,theme)}catch(_){};$('themeToggle').textContent=theme==='dark'?'☀':'◐'}
function initTheme(){let saved;try{saved=localStorage.getItem(STORAGE.theme)}catch(_){};setTheme(saved||(matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'))}
function favorites(){return new Set(readJSON(STORAGE.favorites,[]))}
function detailUrl(course){return `course.html?id=${encodeURIComponent(course.id)}&lang=${encodeURIComponent(currentLang)}`}
function durationText(c){return localizedValue(c.durationLabel)||getText('unknownDuration')}
function listHtml(items){return (items||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join('')}
function simpleCard(course){return `<article class="course-card compact-card"><div class="card-top"><div class="course-logo"><img src="${escapeHtml(course.thumbnail)}" alt=""></div><span class="editorial-score">${course.editorialScore.toFixed(1)}</span></div><div class="card-body"><div class="provider-line"><span>${escapeHtml(course.provider)}</span><small>${escapeHtml(course.platform)}</small></div><h3>${escapeHtml(courseField(course,'title'))}</h3><div class="fact-row"><span>◷ ${escapeHtml(durationText(course))}</span><span>◎ ${escapeHtml(levelLabel(course.level))}</span></div><div class="card-footer"><span></span><a class="details-link" href="${detailUrl(course)}">${getText('details')} ↗</a></div></div></article>`}
function markViewed(course){const views=readJSON(STORAGE.views,{});views[course.id]=(views[course.id]||0)+1;writeJSON(STORAGE.views,views);let recent=readJSON(STORAGE.recent,[]).filter(id=>id!==course.id);recent.unshift(course.id);writeJSON(STORAGE.recent,recent.slice(0,12));return views[course.id]}
function renderRating(course){const labels={content:'rating_content',beginner:'rating_beginner',practical:'rating_practical',certificate:'rating_certificate',timeValue:'rating_timeValue'};return Object.entries(course.ratings||{}).map(([key,val])=>`<div class="rating-item"><div><span>${escapeHtml(getText(labels[key]||key))}</span><b>${Number(val).toFixed(1)}</b></div><div class="rating-track"><i style="width:${Math.max(0,Math.min(100,val*10))}%"></i></div></div>`).join('')}
function renderDetail(course,views){
  document.title=`${courseField(course,'title')} | ${getText('siteName')}`;
  $('courseThumb').src=course.thumbnail;$('courseTitle').textContent=courseField(course,'title');$('courseProvider').textContent=`${course.provider} · ${course.platform}`;$('courseSummary').textContent=courseField(course,'summary');$('officialLink').href=course.sourceUrl;$('courseWhy').textContent=currentLang==='ar'?(course.why_ar||course.summary_ar):course.summary;
  $('detailBadges').innerHTML=`<span class="badge accent">${escapeHtml(categoryLabel(course.category))}</span><span class="badge ${course.free?'good':'soft'}">${course.free?getText('free'):getText('paid')}</span>${course.unionPick?`<span class="badge accent">★ ${getText('developerPick')}</span>`:''}`;
  const facts=[['◷',getText('duration'),durationText(course)],['◎',getText('level'),levelLabel(course.level)],['🌐',getText('language'),(course.language||[]).map(langLabel).join(' / ')],['🎓',getText('certificate'),course.certificate?(course.certificateType_ar&&currentLang==='ar'?course.certificateType_ar:getText('certificate')):getText('noCertificate')],['🏛',getText('platform'),course.platform],['⭐',getText('score'),course.editorialScore.toFixed(1)+'/10'],['👁',getText('localViews'),String(views)],['✦',getText('category'),categoryLabel(course.category)]];
  $('courseFacts').innerHTML=facts.map(([icon,label,value])=>`<div class="decision-item"><span>${icon}</span><div><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong></div></div>`).join('');
  $('courseRatings').innerHTML=renderRating(course);$('courseOutcomes').innerHTML=listHtml(localizedArray(course,'outcomes'));$('courseAudience').innerHTML=listHtml(localizedArray(course,'audience'));$('coursePrerequisites').innerHTML=listHtml(localizedArray(course,'prerequisites'));$('courseSkills').innerHTML=course.skills.map(s=>`<span>${escapeHtml(s)}</span>`).join('');$('courseVerified').textContent=course.lastVerified;
  const next=(course.nextCourseIds||[]).map(id=>COURSES_DATA.find(c=>c.id===id)).filter(Boolean);$('nextCourses').innerHTML=next.length?next.map(simpleCard).join(''):`<p class="muted-copy">—</p>`;
  const similar=COURSES_DATA.filter(c=>c.id!==course.id&&c.category===course.category&&!next.some(n=>n.id===c.id)).sort((a,b)=>b.editorialScore-a.editorialScore).slice(0,3);$('similarCourses').innerHTML=similar.length?similar.map(simpleCard).join(''):`<p class="muted-copy">—</p>`;
  const updateFav=()=>{$('favoriteBtn').classList.toggle('active',favorites().has(course.id));$('favoriteBtn').querySelector('span').textContent=favorites().has(course.id)?getText('removeSaved'):getText('save')};updateFav();$('favoriteBtn').onclick=()=>{const set=favorites();set.has(course.id)?set.delete(course.id):set.add(course.id);writeJSON(STORAGE.favorites,[...set]);updateFav()};
  $('shareBtn').onclick=async()=>{const url=location.href;try{if(navigator.share)await navigator.share({title:courseField(course,'title'),text:courseField(course,'summary'),url});else{await navigator.clipboard.writeText(url);showToast(getText('copied'))}}catch(_){}};
}
function changeLanguage(lang,course,views){setLang(lang);applyTranslations();$('langSwitcher').value=currentLang;renderDetail(course,views)}
document.addEventListener('DOMContentLoaded',()=>{
  const params=new URLSearchParams(location.search);setLang(params.get('lang')||currentLang);initTheme();applyTranslations();$('langSwitcher').value=currentLang;const course=COURSES_DATA.find(c=>c.id===params.get('id'));if(!course){$('detailLoading').hidden=true;$('notFound').hidden=false;return;}const views=markViewed(course);$('detailLoading').hidden=true;$('detailContent').hidden=false;renderDetail(course,views);$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('langSwitcher').onchange=e=>changeLanguage(e.target.value,course,views);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
});
