const $=id=>document.getElementById(id);
const STORAGE_THEME='dunya.theme';
let platform=null, platformCourses=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function key(v){return CourseCatalog.normalizeText(v).replace(/\s+/g,'');}
function localizedPlatform(p){if(currentLang==='en')return p.description_en||p.description||'';if(currentLang==='tr')return p.description_tr||p.description||'';return p.description||'';}
function matchesPlatform(course,p){const k=key(p.name);return [course.platform,course.provider].filter(Boolean).some(v=>{const x=key(v);return x===k||x.includes(k)||k.includes(x)});}
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem(STORAGE_THEME,theme)}catch(_){};$('themeToggle').textContent=theme==='dark'?'☀':'◐';}
function initTheme(){let saved;try{saved=localStorage.getItem(STORAGE_THEME)}catch(_){};const preferred=matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(saved||preferred);}
function courseCard(c){const title=(currentLang==='ar'&&c.title_ar)|| (currentLang==='tr'&&c.title_tr)||c.title||c.name||'Course';const summary=(currentLang==='ar'&&c.summary_ar)|| (currentLang==='tr'&&c.summary_tr)||c.summary||'';const url=c.sourceUrl||c.url||'#';const rich=!!COURSES_DATA.find(x=>x.id===c.id);return `<article class="course-card"><div class="card-top"><div class="course-logo"><img src="${esc(c.thumbnail||platform.thumbnail||'icon.svg')}" alt="" loading="lazy"></div><span class="editorial-score">${c.editorialScore?Number(c.editorialScore).toFixed(1):'↗'}</span></div><div class="card-body"><div class="provider-line"><span>${esc(c.provider||platform.name)}</span><small>${esc(c.platform||platform.name)}</small></div><h3>${esc(title)}</h3><p class="card-summary">${esc(summary||getText('sourceOnlyCourse'))}</p><div class="card-footer"><span>${c.free?'✓ '+getText('free'):''}</span>${rich?`<a class="details-link" href="course.html?id=${encodeURIComponent(c.id)}&lang=${encodeURIComponent(currentLang)}">${getText('details')} ↗</a>`:`<a class="details-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${getText('openOfficial')} ↗</a>`}</div></div></article>`;}
async function loadManifest(){try{const r=await fetch('catalogs/manifest.json',{cache:'no-store'});if(!r.ok)return null;return await r.json();}catch(_){return null;}}
async function loadShard(id,manifest){try{const meta=manifest?.platforms?.[id];const target=meta?.cleanFile||meta?.catalogFile||('catalogs/'+encodeURIComponent(id)+'.json');const r=await fetch(encodeURI(target),{cache:'no-store'});if(!r.ok)return[];const payload=await r.json();if(Array.isArray(payload))return StaticCatalog.clean(payload,platform);if(Array.isArray(payload?.courses))return StaticCatalog.clean(payload.courses,platform);return await StaticCatalog.loadDescriptorCourses(payload,platform);}catch(_){return[];}}
function dedupe(list){const seen=new Set();return list.filter(c=>{const k=c.id||c.sourceUrl||c.url||`${c.platform}:${c.title}`;if(!k||seen.has(k))return false;seen.add(k);return true;});}
function renderCourses(){const q=$('platformCourseSearch').value||'';const list=CourseCatalog.searchCourses(platformCourses,q);$('platformCourseCount').textContent=platformCourses.length;$('platformCoursesGrid').innerHTML=list.length?list.map(courseCard).join(''):`<div class="no-results">⌕<strong>${getText('noResults')}</strong></div>`;}
function renderPlatform(){document.title=`${platform.name} | ${getText('siteName')}`;$('platformLogo').src=platform.thumbnail||'icon.svg';$('platformTitle').textContent=platform.name;$('platformDescription').textContent=localizedPlatform(platform);$('officialCatalogLink').href=platform.link;$('platformMeta').innerHTML=`<span>${platform.free?'✓ '+getText('free'):getText('paid')}</span>${platform.certificate?`<span>🎓 ${getText('certificate')}</span>`:''}<span>🌐 ${esc(platform.language||'')}</span>`;renderCourses();}
async function init(){const params=new URLSearchParams(location.search);setLang(params.get('lang')||currentLang);initTheme();applyTranslations();$('langSwitcher').value=currentLang;platform=PLATFORMS_DATA.find(p=>p.id===params.get('id'))||PLATFORMS_DATA.find(p=>p.id==='plat-1');const curated=COURSES_DATA.filter(c=>matchesPlatform(c,platform));const manifest=await loadManifest();const shard=await loadShard(platform.id,manifest);platformCourses=dedupe([...curated,...shard]);renderPlatform();$('platformCourseSearch').addEventListener('input',renderCourses);$('langSwitcher').onchange=e=>{setLang(e.target.value);applyTranslations();renderPlatform()};$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
document.addEventListener('DOMContentLoaded',init);
